version: "3"
services:
    fwd-server:
        image: coderone.azurecr.io/game-server:259
        environment:
            - TELEMETRY_ENABLED=0
            - PORT=6969
        networks:
            - coderone-tournament-dev
    game-server:
        image: coderone.azurecr.io/game-server:259
        ports:
            - 3000:3000
        environment:
            - PRNG_SEED=1234
            - WORLD_SEED=1234
            - TRAINING_MODE_ENABLED=0
            - TELEMETRY_ENABLED=0
            - TICK_RATE_HZ=1
        networks:
            - coderone-tournament-dev
    python3-agent:
        build:
            context: python3
            dockerfile: Dockerfile
        environment:
            - GAME_CONNECTION_STRING=ws://game-server:3000/?role=agent&agentId=agentId&name=python3-agent
        depends_on:
            - game-server
        networks:
            - coderone-tournament

    python3-fwd:
        build:
            context: python3
            dockerfile: Dockerfile.fwd
        environment:
            - GAME_CONNECTION_STRING=ws://game-server:3000/?role=agent&agentId=agentId&name=python3-agent
            - FWD_MODEL_CONNECTION_STRING=ws://fwd-server:6969/?role=admin
        depends_on:
            - game-server
        networks:
            - coderone-tournament
networks:
    coderone-tournament:
